spring:
  application:
    name: device-api

server:
  port: 8080

logging:
  level:
    root: INFO
    com.devicemanagement.deviceapi: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs
