apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
resources:
  - ../../base
labels:
  - pairs:
      app.kubernetes.io/environment: prod
    includeSelectors: true
replicas:
  - name: admin-portal
    count: 3
  - name: device-api
    count: 3
